// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStoreAdmin.Data;

#nullable disable

namespace WebStoreAdmin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807001623_MiseAJourParfum")]
    partial class MiseAJourParfum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebStoreAdmin.Models.AdresseLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("AdressesLivraison");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surnom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ArticleCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ParfumId");

                    b.ToTable("ArticlesCommande");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Avis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.ToTable("Categorie", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Nom = "Floral"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Nom = "Woody"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Nom = "Oriental"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Nom = "Fresh"
                        });
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.FamilleOlfactive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FamilleOlfactive", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Agrumes"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Fruitée"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Florale"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Épicée"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Aromatique"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Boisée"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Orientale"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Gourmande"
                        },
                        new
                        {
                            Id = 9,
                            Nom = "Fixateur synthétique"
                        },
                        new
                        {
                            Id = 10,
                            Nom = "Aquatique"
                        },
                        new
                        {
                            Id = 11,
                            Nom = "Verte"
                        },
                        new
                        {
                            Id = 12,
                            Nom = "Cuirée"
                        },
                        new
                        {
                            Id = 13,
                            Nom = "Fougère"
                        },
                        new
                        {
                            Id = 14,
                            Nom = "Chyprée"
                        });
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ImageParfum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ImagePrincipale")
                        .HasColumnType("bit");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("int");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParfumId");

                    b.ToTable("ImagesParfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<string>("NomParfum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ParfumId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.LignePanier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PanierId")
                        .HasColumnType("int");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.Property<double>("PrixUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.HasIndex("ParfumId");

                    b.ToTable("LignesPanier");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.NoteOlfactive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FamilleOlfactiveId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FamilleOlfactiveId");

                    b.ToTable("NoteOlfactive", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Bergamote"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Citron"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Citron vert"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Mandarine"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Mandarine verte"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Orange"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Orange sanguine"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Pamplemousse"
                        },
                        new
                        {
                            Id = 9,
                            Nom = "Yuzu"
                        },
                        new
                        {
                            Id = 10,
                            Nom = "Combava"
                        },
                        new
                        {
                            Id = 11,
                            Nom = "Néroli"
                        },
                        new
                        {
                            Id = 12,
                            Nom = "Petit grain"
                        },
                        new
                        {
                            Id = 13,
                            Nom = "Pomme"
                        },
                        new
                        {
                            Id = 14,
                            Nom = "Pomme verte"
                        },
                        new
                        {
                            Id = 15,
                            Nom = "Poire"
                        },
                        new
                        {
                            Id = 16,
                            Nom = "Pêche"
                        },
                        new
                        {
                            Id = 17,
                            Nom = "Abricot"
                        },
                        new
                        {
                            Id = 18,
                            Nom = "Prune"
                        },
                        new
                        {
                            Id = 19,
                            Nom = "Cerise"
                        },
                        new
                        {
                            Id = 20,
                            Nom = "Fraise"
                        },
                        new
                        {
                            Id = 21,
                            Nom = "Framboise"
                        },
                        new
                        {
                            Id = 22,
                            Nom = "Mûre"
                        },
                        new
                        {
                            Id = 23,
                            Nom = "Cassis"
                        },
                        new
                        {
                            Id = 24,
                            Nom = "Groseille"
                        },
                        new
                        {
                            Id = 25,
                            Nom = "Litchi"
                        },
                        new
                        {
                            Id = 26,
                            Nom = "Ananas"
                        },
                        new
                        {
                            Id = 27,
                            Nom = "Mangue"
                        },
                        new
                        {
                            Id = 28,
                            Nom = "Fruit de la passion"
                        },
                        new
                        {
                            Id = 29,
                            Nom = "Melon"
                        },
                        new
                        {
                            Id = 30,
                            Nom = "Pastèque"
                        },
                        new
                        {
                            Id = 31,
                            Nom = "Noix de coco"
                        },
                        new
                        {
                            Id = 32,
                            Nom = "Banane"
                        },
                        new
                        {
                            Id = 33,
                            Nom = "Figue"
                        },
                        new
                        {
                            Id = 34,
                            Nom = "Datte"
                        },
                        new
                        {
                            Id = 35,
                            Nom = "Rose"
                        },
                        new
                        {
                            Id = 36,
                            Nom = "Rose bulgare"
                        },
                        new
                        {
                            Id = 37,
                            Nom = "Rose de Mai"
                        },
                        new
                        {
                            Id = 38,
                            Nom = "Jasmin"
                        },
                        new
                        {
                            Id = 39,
                            Nom = "Jasmin sambac"
                        },
                        new
                        {
                            Id = 40,
                            Nom = "Tubéreuse"
                        },
                        new
                        {
                            Id = 41,
                            Nom = "Ylang-Ylang"
                        },
                        new
                        {
                            Id = 42,
                            Nom = "Gardénia"
                        },
                        new
                        {
                            Id = 43,
                            Nom = "Fleur d'oranger"
                        },
                        new
                        {
                            Id = 44,
                            Nom = "Muguet"
                        },
                        new
                        {
                            Id = 45,
                            Nom = "Pivoine"
                        },
                        new
                        {
                            Id = 46,
                            Nom = "Magnolia"
                        },
                        new
                        {
                            Id = 47,
                            Nom = "Iris"
                        },
                        new
                        {
                            Id = 48,
                            Nom = "Violette"
                        },
                        new
                        {
                            Id = 49,
                            Nom = "Freesia"
                        },
                        new
                        {
                            Id = 50,
                            Nom = "Œillet"
                        },
                        new
                        {
                            Id = 51,
                            Nom = "Héliotrope"
                        },
                        new
                        {
                            Id = 52,
                            Nom = "Mimosa"
                        },
                        new
                        {
                            Id = 53,
                            Nom = "Lilas"
                        },
                        new
                        {
                            Id = 54,
                            Nom = "Lotus"
                        },
                        new
                        {
                            Id = 55,
                            Nom = "Narcisse"
                        },
                        new
                        {
                            Id = 56,
                            Nom = "Poivre noir"
                        },
                        new
                        {
                            Id = 57,
                            Nom = "Poivre rose"
                        },
                        new
                        {
                            Id = 58,
                            Nom = "Cardamome"
                        },
                        new
                        {
                            Id = 59,
                            Nom = "Cannelle"
                        },
                        new
                        {
                            Id = 60,
                            Nom = "Safran"
                        },
                        new
                        {
                            Id = 61,
                            Nom = "Clou de girofle"
                        },
                        new
                        {
                            Id = 62,
                            Nom = "Noix de muscade"
                        },
                        new
                        {
                            Id = 63,
                            Nom = "Gingembre"
                        },
                        new
                        {
                            Id = 64,
                            Nom = "Baies roses"
                        },
                        new
                        {
                            Id = 65,
                            Nom = "Cumin"
                        },
                        new
                        {
                            Id = 66,
                            Nom = "Anis étoilé"
                        },
                        new
                        {
                            Id = 67,
                            Nom = "Lavande"
                        },
                        new
                        {
                            Id = 68,
                            Nom = "Romarin"
                        },
                        new
                        {
                            Id = 69,
                            Nom = "Thym"
                        },
                        new
                        {
                            Id = 70,
                            Nom = "Sauge"
                        },
                        new
                        {
                            Id = 71,
                            Nom = "Menthe"
                        },
                        new
                        {
                            Id = 72,
                            Nom = "Basilic"
                        },
                        new
                        {
                            Id = 73,
                            Nom = "Estragon"
                        },
                        new
                        {
                            Id = 74,
                            Nom = "Absinthe"
                        },
                        new
                        {
                            Id = 75,
                            Nom = "Bois de santal"
                        },
                        new
                        {
                            Id = 76,
                            Nom = "Cèdre de Virginie"
                        },
                        new
                        {
                            Id = 77,
                            Nom = "Cèdre Atlas"
                        },
                        new
                        {
                            Id = 78,
                            Nom = "Bois de gaïac"
                        },
                        new
                        {
                            Id = 79,
                            Nom = "Vétiver"
                        },
                        new
                        {
                            Id = 80,
                            Nom = "Patchouli"
                        },
                        new
                        {
                            Id = 81,
                            Nom = "Oud"
                        },
                        new
                        {
                            Id = 82,
                            Nom = "Cyprès"
                        },
                        new
                        {
                            Id = 83,
                            Nom = "Pin"
                        },
                        new
                        {
                            Id = 84,
                            Nom = "Cachemire"
                        },
                        new
                        {
                            Id = 85,
                            Nom = "Ambre"
                        },
                        new
                        {
                            Id = 86,
                            Nom = "Benjoin"
                        },
                        new
                        {
                            Id = 87,
                            Nom = "Encens"
                        },
                        new
                        {
                            Id = 88,
                            Nom = "Myrrhe"
                        },
                        new
                        {
                            Id = 89,
                            Nom = "Labdanum"
                        },
                        new
                        {
                            Id = 90,
                            Nom = "Opoponax"
                        },
                        new
                        {
                            Id = 91,
                            Nom = "Baume du Pérou"
                        },
                        new
                        {
                            Id = 92,
                            Nom = "Vanille"
                        },
                        new
                        {
                            Id = 93,
                            Nom = "Fève Tonka"
                        },
                        new
                        {
                            Id = 94,
                            Nom = "Caramel"
                        },
                        new
                        {
                            Id = 95,
                            Nom = "Praliné"
                        },
                        new
                        {
                            Id = 96,
                            Nom = "Chocolat"
                        },
                        new
                        {
                            Id = 97,
                            Nom = "Cacao"
                        },
                        new
                        {
                            Id = 98,
                            Nom = "Miel"
                        },
                        new
                        {
                            Id = 99,
                            Nom = "Sucre"
                        },
                        new
                        {
                            Id = 100,
                            Nom = "Guimauve"
                        },
                        new
                        {
                            Id = 101,
                            Nom = "Amande"
                        },
                        new
                        {
                            Id = 102,
                            Nom = "Noisette"
                        },
                        new
                        {
                            Id = 103,
                            Nom = "Café"
                        },
                        new
                        {
                            Id = 104,
                            Nom = "Lait"
                        },
                        new
                        {
                            Id = 105,
                            Nom = "Musc blanc"
                        },
                        new
                        {
                            Id = 106,
                            Nom = "Ambroxan"
                        },
                        new
                        {
                            Id = 107,
                            Nom = "Musc"
                        },
                        new
                        {
                            Id = 108,
                            Nom = "Cashmeran"
                        },
                        new
                        {
                            Id = 109,
                            Nom = "Iso E Super"
                        },
                        new
                        {
                            Id = 110,
                            Nom = "Civette"
                        },
                        new
                        {
                            Id = 111,
                            Nom = "Notes marines"
                        },
                        new
                        {
                            Id = 112,
                            Nom = "Sel marin"
                        },
                        new
                        {
                            Id = 113,
                            Nom = "Algues"
                        },
                        new
                        {
                            Id = 114,
                            Nom = "Herbe coupée"
                        },
                        new
                        {
                            Id = 115,
                            Nom = "Feuille de violette"
                        },
                        new
                        {
                            Id = 116,
                            Nom = "Feuille de tomate"
                        },
                        new
                        {
                            Id = 117,
                            Nom = "Thé vert"
                        },
                        new
                        {
                            Id = 118,
                            Nom = "Maté"
                        },
                        new
                        {
                            Id = 119,
                            Nom = "Cuir"
                        },
                        new
                        {
                            Id = 120,
                            Nom = "Tabac"
                        },
                        new
                        {
                            Id = 121,
                            Nom = "Fumée"
                        },
                        new
                        {
                            Id = 122,
                            Nom = "Whisky"
                        },
                        new
                        {
                            Id = 123,
                            Nom = "Rhum"
                        },
                        new
                        {
                            Id = 124,
                            Nom = "Cognac"
                        });
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Panier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Parfum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<int?>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("WishlistId");

                    b.ToTable("Parfums");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ParfumNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NoteOlfactiveId")
                        .HasColumnType("int");

                    b.Property<int>("ParfumId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteOlfactiveId");

                    b.HasIndex("ParfumId");

                    b.ToTable("ParfumNotes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebStoreAdmin.Models.AdresseLivraison", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ArticleCommande", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.Parfum", "Parfum")
                        .WithMany("ArticlesCommande")
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Client", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("WebStoreAdmin.Models.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Commande", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Employe", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("WebStoreAdmin.Models.Employe", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ImageParfum", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Parfum", "Parfum")
                        .WithMany("Images")
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.LigneCommande", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.Parfum", "Parfum")
                        .WithMany()
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.LignePanier", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Panier", "Panier")
                        .WithMany("Lignes")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.Parfum", "Parfum")
                        .WithMany()
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.NoteOlfactive", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.FamilleOlfactive", "FamilleOlfactive")
                        .WithMany("Notes")
                        .HasForeignKey("FamilleOlfactiveId");

                    b.Navigation("FamilleOlfactive");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Paiement", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Panier", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Parfum", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.Categorie", "Categorie")
                        .WithMany("Parfums")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.Wishlist", null)
                        .WithMany("Parfums")
                        .HasForeignKey("WishlistId");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.ParfumNote", b =>
                {
                    b.HasOne("WebStoreAdmin.Models.NoteOlfactive", "NoteOlfactive")
                        .WithMany("ParfumNotes")
                        .HasForeignKey("NoteOlfactiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebStoreAdmin.Models.Parfum", "Parfum")
                        .WithMany("Notes")
                        .HasForeignKey("ParfumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteOlfactive");

                    b.Navigation("Parfum");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Categorie", b =>
                {
                    b.Navigation("Parfums");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.FamilleOlfactive", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.NoteOlfactive", b =>
                {
                    b.Navigation("ParfumNotes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Panier", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Parfum", b =>
                {
                    b.Navigation("ArticlesCommande");

                    b.Navigation("Images");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("WebStoreAdmin.Models.Wishlist", b =>
                {
                    b.Navigation("Parfums");
                });
#pragma warning restore 612, 618
        }
    }
}
